name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: 'praxisev_0'
            server: 'www566.your-server.de'
            password: ${{ secrets.SFTP_PASSWORD }}
            local_path: './build/*'
            remote_path: '/'
            sftpArgs: '-o ConnectTimeout=5'

